version: "3"
services:
  sql:
    image: mysql:8.0.32
    restart: always
    container_name: "sql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "demo"
      MYSQL_USER: "demo"
      MYSQL_PASSWORD: "password"
    volumes:
      - ./:/docker-entrypoint-initdb.d/
      - ./mysql.cnf:/etc/mysql/conf.d/my.cnf
      - ./settings:/var/lib/mysql
